name: Presubmits

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  presubmit:

    runs-on: ubuntu-latest
    container: "rust:latest"

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose --release
      - name: Check format
        run: |
          rustup component add rustfmt
          cargo fmt --check --verbose
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets -- -D warnings
